# docker-compose.yml

version: '3.8'

services:
  web:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0'
    volumes:
      - .:/app
    ports:
      - 8080:8000
    environment:
      - DATABASE_URL=postgresql://psuser:ps1234@db:5432/appDB
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=psuser
      - POSTGRES_PASSWORD=ps1234
      - POSTGRES_DB=appDB

volumes:
  postgres_data:
